### ISSUE TITLE
建议：默认的 questioner 应该是在右边（right），AI 应该是在左边（left）

### ISSUE THREAD

**Issue by halooojustin** [AIOS-club/ai-chat-export#9]
当前导出的是 
```
  characters:
    - name: questioner
      avatar: https://res.pandateacher.com/1O2BGDK91671292227563.jpg
    - name: AI
      direction: right
      avatar: https://res.pandateacher.com/WDNS259R1677122357140.png
```
